# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://ukk.no'
baseurl: ''
title: 'Universitetets karateklubb'
description: 'Heim for UKK'
permalink: pretty
logo: "/assets/uploads/crest-52.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Heim
  url: /
- title: Treningstider
  url: /treningstider/
- title: Om UKK
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Til toppen
  url: "#top"

# Collections
collections:
  posts:
    title: Nyhende og artiklar
    output: true
    description: ""
    feature_text: |
      Nyhende og artiklar
    feature_image: "https://picsum.photos/2560/600?image=866"